### ISSUE TITLE
Plot utils

### ISSUE THREAD

**Issue by JLrumberger** [angelolab/cell_classification#15]
**Section 1: Design details**

To check if dataset creation with #1 gives correct results on real world data, we'll use a plot helper function that takes in a marker channel and the positive/negative/unspecific (1/0/2) channel and visualizes the cell boundaries in different colors for the different classes. It should also have the option to write PNGs to path if available.

**Relevant background**

We want to generate plots for sanity checking the generated labels and input data which is produced by #1. 

**Design overview**

We will load a serialized example produced by #1, use the `parse_example` function to make it a dictionary. The dictionary is then passed to a plotting function that plots the marker image and transforms the marker activity mask to boundaries. Then the boundaries are colored based on their value (1/0/2) and overlayed on the plot. A legend tells you the color of the marker values in the overlay.

**Design list/flowchart**

1. dataloader: loads examples from tfrecord
2. parse function: parsed loaded examples to dict
3. plot function: takes dict, calls boundary transform plotting function and returns plot or saves it to path
4. boundary transform plotting helper function: takes in a mask image, generates boundaries and assigns values to the boundaries based on the value of the object.

**Required inputs**

- serialized tfrecord examples with keys `["mplex_img", "binary_mask", "instance_mask", "imaging_platform", "marker_activity_mask", "dataset", "marker", "activity_df", "folder_name"]`
- path to store plots

**Output files**

Plots showing an overlay of marker channels and marker activity.

**Section 2: Implementation details**

Once you have completed section 1, please tag the relevant parties and iterate on the initial design details until everyone is satisfied. Then, 
proceed to section 2

**Control flow**

Provide additional, more granular details (if necessary) about how the proposed coding logic will be put together

**Milestones and timeline**

List each of the major components of the project, and provide an estimated completion date for each one.

**Comment by ngreenwald** [comment]
Rater than an overlay, I think it will be better to separately plot the channel data in one image, and the marker_intensity mask in an adjacent image, but you can try both and see which one you like better.  Looks good!
