### ISSUE TITLE
Put argparse CLI in plot_utils in a separate function and write tests for it

### ISSUE THREAD

**Issue by JLrumberger** [angelolab/cell_classification#17]
**Is your feature request related to a problem? Please describe.**

Test coverage in `plot_utils` is too low, to increase it we need to also test the CLI. Thus we need to put the CLI related code from main into it's own function and then write tests for it

**Describe the solution you'd like**

Put all the argparse stuff from main into its own function

**Describe alternatives you've considered**

None

**Comment by ngreenwald** [comment]
This will be good to do eventually, but definitely not top priority.
