### ISSUE TITLE
Cannot find /data/example_dataset/input_data folder in repo

### ISSUE THREAD

**Issue by Calebium** [angelolab/cell_classification#72]
Hi,

In the templates folder, the 1_Nimbus_Predict.ipynb notebook suggests that there is a data folder with some example datasets. However, I cannot seem to find the data folder in the main branch. Has it been omitted in the latest release? I'm trying to follow the jupyter notebook to perform prediction on some data.

Thanks!

Caleb

**Comment by srivarra** [comment]
Hi @Calebium, thanks for checking out Nimbus!

The example dataset can be downloaded by running the cell containing the following function

```python
example_dataset.get_example_dataset(dataset="cluster_pixels", save_dir = base_dir, overwrite_existing = False)
```

Let me know if that helps.

The data gets saved in a newly created `data` folder.
