### ISSUE TITLE
Dimensions are swapped on output

### ISSUE THREAD

**Issue by ngreenwald** [angelolab/cell_classification#81]
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
"I noticed that there's a bug in the output nimbus image shape - it appears to swap x and y dimensions from the input. For example, the input image and segmentation mask for a run I had was (2924, 3285), and the resulting output nimbus image was (3295, 2924). The underlying classification looks correct, it's just the dimensions of the image that are wrong. I was using your [1_Nimbus_Predict template](https://github.com/angelolab/Nimbus/blob/main/templates/1_Nimbus_Predict.ipynb), and the critical line of code was cell_table = nimbus.predict_fovs()"

**Expected behavior**
Input and output images have same shape

**To Reproduce**
![Screenshot 2024-06-11 at 1 14 02 PM](https://github.com/angelolab/Nimbus/assets/13770365/5869c325-9c26-4ec6-9305-a692ea247601)

Got this from @peterjchou

**Comment by JLrumberger** [comment]
Should be fixed in our latest version of [Nimbus-Inference](https://github.com/angelolab/Nimbus-Inference)
